apiVersion: v1
kind: Template
labels:
  app: draw
  template: draw-buildconfig-with-secret
message: |-
  For more information about using this template, see https://github.com/Worteks/wsweet-ci
metadata:
  annotations:
    description: Draw - BuildConfig with Secret
      see https://github.com/Worteks/docker-draw
    iconClass: icon-java
    openshift.io/display-name: Draw
    openshift.io/documentation-url: https://github.com/Worteks/wsweet-ci
    openshift.io/provider-display-name: Worteks
    openshift.io/support-url: https://www.worteks.com
    tags: draw
  name: draw-buildconfig-with-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-username: "{.data['username']}"
    name: git-${FRONTNAME}-${DRAW_REPOSITORY_REF}
  stringData:
    username: "${GIT_DEPLOYMENT_TOKEN}"
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds Wsweet Draw images
    labels:
      name: draw-${FRONTNAME}-${DRAW_REPOSITORY_REF}
    name: draw-${FRONTNAME}-${DRAW_REPOSITORY_REF}
  spec:
    failedBuildsHistoryLimit: 1
    resources:
      limits:
        cpu: 200m
        memory: 1Gi
    source:
      contextDir: /
      git:
        uri: ${DRAW_REPOSITORY_URL}
        ref: "${DRAW_REPOSITORY_REF}"
      sourceSecret:
        name: git-${FRONTNAME}-${DRAW_REPOSITORY_REF}
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: DO_UPGRADE
          value: foo
        forcePull: false
    output:
      to:
        kind: ImageStreamTag
        name: draw-${FRONTNAME}:${DRAW_REPOSITORY_REF}
    triggers:
    - type: ImageChange
    - type: ConfigChange
parameters:
- name: DRAW_REPOSITORY_REF
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch
  displayName: Git Reference
  required: true
  value: master
- name: DRAW_REPOSITORY_URL
  description: The URL of the repository with your Draw Dockerfile
  displayName: Git Repository URL
  required: true
  value: https://github.com/Worteks/docker-draw.git
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
- name: GIT_DEPLOYMENT_TOKEN
  description: Git deployment token
  displayName: Git Deployment Token
  required: true
