apiVersion: v1
kind: Template
labels:
  app: draw
  template: draw-imagestream
message: |-
  For more information about using this template, see https://github.com/Worteks/wsweet-ci
metadata:
  annotations:
    description: Draw - ImageStream
      see https://github.com/Worteks/docker-draw
    iconClass: icon-java
    openshift.io/display-name: Draw
    openshift.io/documentation-url: https://github.com/Worteks/wsweet-ci
    openshift.io/provider-display-name: Worteks
    openshift.io/support-url: https://www.worteks.com
    tags: draw
  name: draw-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in Wsweet Draw image
    name: draw-${FRONTNAME}
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
